# Site settings
title: dsanel
email: dsanel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dsanel.github.io" # the base hostname & protocol for your site
twitter_username: dsanel
github_username:  dsanel

# Build settings
markdown: kramdown
